// src/app/api/contact/route.ts
// ─────────────────────────────────────────────────────────────────────────────
// PURPOSE: Handles contact form submissions.
//          Route: POST /api/contact
//
// STEPS:
//   1. Parse request body as JSON
//   2. Validate with Zod (server-side — NEVER skip this!)
//   3. Insert into PostgreSQL via Drizzle ORM
//   4. (Optional) Send you an email via Resend
//   5. Return 201 Created
//
// WHY VALIDATE AGAIN? (Contact.tsx already validates client-side)
//   Anyone can bypass your React form with curl, Postman, or DevTools.
//   Client validation = UX convenience only.
//   Server validation = actual security.
//   ALWAYS validate on the server, regardless of client validation.
// ─────────────────────────────────────────────────────────────────────────────

import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/db";
import { contactMessages } from "@/db/schema";

const schema = z.object({
  name:    z.string().min(2).max(50),
  email:   z.string().email(),
  subject: z.string().min(5).max(100),
  message: z.string().min(20).max(2000),
});

export async function POST(request: NextRequest) {
  try {
    const body   = await request.json();
    const result = schema.safeParse(body);

    if (!result.success) {
      return NextResponse.json(
        {
          error:  "Validation failed",
          issues: result.error.issues.map(i => ({
            field:   i.path.join("."),
            message: i.message,
          })),
        },
        { status: 400 }
      );
    }

    const { name, email, subject, message } = result.data;

    // Insert into database
    // Drizzle: await db.insert(table).values({ columns })
    // = INSERT INTO contact_messages (name, email, subject, message) VALUES (...)
    // id and created_at are auto-generated by the database
    await db.insert(contactMessages).values({ name, email, subject, message });

    // ── Optional: Resend email notification ────────────────────────────────
    // Uncomment this AFTER verifying the form saves to DB first.
    // Requires RESEND_API_KEY in .env.local and Vercel environment variables.
    
    try {
      const { Resend } = await import("resend");
      const resend = new Resend(process.env.RESEND_API_KEY);
      await resend.emails.send({
        from:    "Portfolio <onboarding@resend.dev>",
        to:      "digitalmail372@gmail.com",   // ← UPDATE: your real email
        subject: `Portfolio message: ${subject}`,
        text:    `From: ${name} <${email}>\n\n${message}`,
        html: `
          <h2 style="color:#7c3aed">New Portfolio Message</h2>
          <p><strong>From:</strong> ${name} (${email})</p>
          <p><strong>Subject:</strong> ${subject}</p>
          <hr />
          <p style="white-space:pre-wrap">${message}</p>
        `,
      });
    } catch (emailError) {
      // Email failure should NOT fail the whole request
      // The DB insert succeeded — that's the important part
      console.error("[contact] Email send failed:", emailError);
    }
    

    return NextResponse.json(
      { success: true, message: "Message saved!" },
      { status: 201 }
    );

  } catch (error) {
    console.error("[/api/contact] Error:", error);
    return NextResponse.json(
      { error: "Failed to save message. Please email directly." },
      { status: 500 }
    );
  }
}